### PR TITLE
Add support for debian packaging to tac_plus

### PR DESCRIPTION
**Pull request by robshakir**
Hi Cooper, facebook Folks!

I wanted to use your fork of tac_plus on a TACACS+ server running Debian, and hence created some ability to package it for both Debian 8 (Jessie) and Debian 7 (Wheezy). It's getting some testing in the network I rolled it into.

I'm happy to maintain this in a separate repository, but I was wondering whether you'd be interested in merging it. No substantial code changes are made other than packaging  - and the binary packages for the amd64 architecture are at http://m.rob.sh/deb/.

Thanks!
r.

### CODE REVIEW

**Comment by cooperlees** [comment]
Hi SIr, Awesome to hear it's working for you. The more using this the better - We are by no means proud that we are using this code base but it gets the job done :P Will pull it on in after I take one more look.

**Comment by cooperlees** [comment]
It was just a larger refactor than building to binaries and I wanted to make minimal changes so I introduced minimal bugs. Got better things to do than play with tacacs+. E.g. making devices that don't need tacacs and can use normal Linux auth like our server fleet - FBOSS ftw.

**Comment by nemith** [comment]
We should file a seperate issue to track properly binding to v6 and v4

**Comment by davidrothera** [comment]
Agreed, looking at the code, supporting a tcp46 is going to take a significant refactor, probably best to either have it as two packages or a single package that provides two binaries (my preference would be the latter).

**Comment by cooperlees** [comment]
LGTM - Thanks Rob.

**Comment by robshakir** [comment]
Thanks - I've just been testing this on our live TACACS+ servers, and was going to update today. Seems to be working well.

Thanks again for your work on this!

**Pull request merged**
